/**
 * This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run the @cosmwasm/ts-codegen generate command to regenerate this file.
 */

export type AndrAddr = string;
export interface InstantiateMsg {
  kernel_address: string;
  owner?: string | null;
  token_address: AndrAddr;
}
export type ExecuteMsg =
  | {
      cancel_sale: {
        asset: Asset;
      };
    }
  | {
      cancel_redeem: {
        asset: Asset;
      };
    }
  | {
      purchase: {
        recipient?: Recipient | null;
      };
    }
  | {
      start_redeem: {
        end_time?: Milliseconds | null;
        exchange_rate: Decimal256;
        recipient?: Recipient | null;
        redeem_asset: Asset;
        start_time?: Expiry | null;
      };
    }
  | {
      replenish_redeem: {
        redeem_asset: Asset;
      };
    }
  | {
      redeem: {
        recipient?: Recipient | null;
      };
    }
  | {
      receive: Cw20ReceiveMsg;
    }
  | {
      amp_receive: AMPPkt;
    }
  | {
      ownership: OwnershipMessage;
    }
  | {
      update_kernel_address: {
        address: Addr;
      };
    }
  | {
      update_app_contract: {
        address: string;
      };
    }
  | {
      permissioning: PermissioningMessage;
    };
export type Asset =
  | {
      cw20_token: AndrAddr;
    }
  | {
      native_token: string;
    };
export type Binary = string;
export type Milliseconds = number;
export type Decimal256 = string;
export type Expiry =
  | {
      from_now: Milliseconds;
    }
  | {
      at_time: Milliseconds;
    };
export type Uint128 = string;
export type ReplyOn = 'always' | 'error' | 'success' | 'never';
export type OwnershipMessage =
  | ('revoke_ownership_offer' | 'accept_ownership' | 'disown')
  | {
      update_owner: {
        expiration?: Expiry | null;
        new_owner: Addr;
      };
    };
export type Addr = string;
export type PermissioningMessage =
  | {
      set_permission: {
        action: string;
        actors: AndrAddr[];
        permission: Permission;
      };
    }
  | {
      remove_permission: {
        action: string;
        actors: AndrAddr[];
      };
    }
  | {
      permission_action: {
        action: string;
      };
    }
  | {
      disable_action_permissioning: {
        action: string;
      };
    };
export type Permission =
  | {
      local: LocalPermission;
    }
  | {
      contract: AndrAddr;
    };
export type LocalPermission =
  | {
      blacklisted: {
        expiration?: Expiry | null;
        start?: Expiry | null;
      };
    }
  | {
      limited: {
        expiration?: Expiry | null;
        start?: Expiry | null;
        uses: number;
      };
    }
  | {
      whitelisted: {
        expiration?: Expiry | null;
        start?: Expiry | null;
      };
    };
export interface Recipient {
  address: AndrAddr;
  ibc_recovery_address?: AndrAddr | null;
  msg?: Binary | null;
}
export interface Cw20ReceiveMsg {
  amount: Uint128;
  msg: Binary;
  sender: string;
}
export interface AMPPkt {
  ctx: AMPCtx;
  messages: AMPMsg[];
}
export interface AMPCtx {
  id?: string | null;
  origin: string;
  origin_username?: AndrAddr | null;
  previous_hops?: CrossChainHop[];
  previous_sender: string;
}
export interface CrossChainHop {
  address: string;
  channel: string;
  from_chain: string;
  funds: Coin[];
  to_chain: string;
  username?: AndrAddr | null;
}
export interface Coin {
  amount: Uint128;
  denom: string;
}
export interface AMPMsg {
  config: AMPMsgConfig;
  funds: Coin[];
  message: Binary;
  recipient: AndrAddr;
}
export interface AMPMsgConfig {
  direct: boolean;
  exit_at_error: boolean;
  gas_limit?: number | null;
  ibc_config?: IBCConfig | null;
  reply_on: ReplyOn;
}
export interface IBCConfig {
  recovery_addr?: AndrAddr | null;
}
export type QueryMsg =
  | {
      sale: {
        asset: string;
      };
    }
  | {
      redeem: {
        asset: Asset;
      };
    }
  | {
      token_address: {};
    }
  | {
      sale_assets: {
        limit?: number | null;
        start_after?: string | null;
      };
    }
  | {
      owner: {};
    }
  | {
      ownership_request: {};
    }
  | {
      type: {};
    }
  | {
      kernel_address: {};
    }
  | {
      app_contract: {};
    }
  | {
      original_publisher: {};
    }
  | {
      block_height_upon_creation: {};
    }
  | {
      version: {};
    }
  | {
      a_d_o_base_version: {};
    }
  | {
      permissions: {
        actor: string;
        limit?: number | null;
        start_after?: string | null;
      };
    }
  | {
      permissioned_actions: {};
    };
export interface ADOBaseVersionResponse {
  version: string;
}
export interface AppContractResponse {
  app_contract: Addr;
}
export interface BlockHeightResponse {
  block_height: number;
}
export interface KernelAddressResponse {
  kernel_address: Addr;
}
export interface PublisherResponse {
  original_publisher: string;
}
export interface ContractOwnerResponse {
  owner: string;
}
export interface ContractPotentialOwnerResponse {
  expiration?: Milliseconds | null;
  potential_owner?: Addr | null;
}
export type ArrayOfString = string[];
export type ArrayOfPermissionInfo = PermissionInfo[];
export interface PermissionInfo {
  action: string;
  actor: string;
  permission: Permission;
}
export interface RedeemResponse {
  redeem?: Redeem | null;
}
export interface Redeem {
  amount: Uint128;
  amount_paid_out: Uint128;
  asset: Asset;
  end_time?: Milliseconds | null;
  exchange_rate: Decimal256;
  recipient: Recipient;
  start_time: Milliseconds;
}
export interface SaleResponse {
  sale?: Sale | null;
}
export interface Sale {
  end_time?: Milliseconds | null;
  exchange_rate: Uint128;
  recipient: Recipient;
  remaining_amount: Uint128;
  start_amount: Uint128;
  start_time: Milliseconds;
}
export interface SaleAssetsResponse {
  assets: string[];
}
export interface TokenAddressResponse {
  address: string;
}
export interface TypeResponse {
  ado_type: string;
}
export interface VersionResponse {
  version: string;
}
export type Cw20ExchangeContractTsExecuteMsg = ExecuteMsg;
